import { InferSelectModel, InferInsertModel } from "drizzle-orm";
import {
  departments,
  users,
  tickets,
  chatMessages,
  userRoleEnum,
  ticketStatusEnum,
  ticketPriorityEnum,
} from "@/infrastructure/db/schema"; // Ajuste o caminho de acordo com a sua estrutura de pastas

// ======================================================
// 1. ENUMS DO BANCO (Tipos textuais extraídos dos pgEnums)
// ======================================================
export type UserRole = (typeof userRoleEnum.enumValues)[number];
// -> "CLIENT" | "AGENT" | "ADMIN"

export type TicketStatus = (typeof ticketStatusEnum.enumValues)[number];
// -> "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED"

export type TicketPriority = (typeof ticketPriorityEnum.enumValues)[number];
// -> "LOW" | "MEDIUM" | "HIGH" | "URGENT"

// ======================================================
// 2. MODELOS DE SELEÇÃO (O que retorna do banco em um SELECT)
// ======================================================
export type Department = InferSelectModel<typeof departments>;
export type User = InferSelectModel<typeof users>;
export type Ticket = InferSelectModel<typeof tickets>;  
export type ChatMessage = InferSelectModel<typeof chatMessages>;

// ======================================================
// 3. MODELOS DE INSERÇÃO (O que enviamos ao banco em um INSERT)
// Campos com default() ou autogenerated (ex: id, createdAt) são OPCIONAIS aqui.
// ======================================================
export type NewDepartment = InferInsertModel<typeof departments>;
export type NewUser = InferInsertModel<typeof users>;
export type NewTicket = InferInsertModel<typeof tickets>;
export type NewChatMessage = InferInsertModel<typeof chatMessages>;

// ======================================================
// 4. ENTIDADES COM RELACIONAMENTOS (Joins frequentes no Drizzle)
// ======================================================

// Ticket completo com todas as entidades associadas (para telas de detalhes do chamado)
export type TicketWithRelations = Ticket & {
  customer: User;
  assignedAgent?: User | null;
  department: Department;
  comments?: (ChatMessage & {
    author: User;
  })[];
};

// Usuário com o seu departamento vinculado
export type UserWithDepartment = User & {
  department?: Department | null;
};

export type ChatMessageWithUser = ChatMessage & {
  user: User;
};